task: '1YCR'
protocol: "binder"
root_out_dir: "/mnt/nas1/alphafold-design/output_test"
# Currently seed is not used for deterministic, but used in out filenames.
seed: 12
enable_disulfide: true

input_pdb_file: "alphafold_design/demo_data/pdb/1ycr/1YCR.pdb"
target_chain: "A"
target_hotspot: ""
target_flexible: false

# ideal short peptide length range: 5-8
binder_len: 12
# CGGGGC as start sequence.
binder_seq: ""

# [0, 1, 3, 6]
num_recycles: 3
recycle_mode: "sample"
num_models: 5
use_multimer: True

max_loop_count: 1

# "pssm_semigreedy", "3stage", "semigreedy", "pssm", "logits", "soft", "hard"
optimizer_protocol: "pssm_semigreedy"
soft_iters: 2
hard_iters: 2
# "adabelief", "adafactor", "adagrad", "adam", "adamw", "fromage", "lamb", "lars", "noisy_sgd", "dpsgd", "radam", "rmsprop", "sgd", "sm3", "yogi"
gd_method: "sgd"
learning_rate: 0.05
norm_seq_grad: True
dropout: True

af_data_path: "/mnt/sda/alphafold/af_data"